extensions:
    pim-job-instance-csv-attribute-export-edit-form:
        module: pim/form/common/edit-form

    pim-job-instance-csv-attribute-export-edit-form-cache-invalidator:
        module: pim/cache-invalidator
        parent: pim-job-instance-csv-attribute-export-edit-form
        position: 1000

    pim-job-instance-csv-attribute-export-edit-form-tabs:
        module: pim/form/common/form-tabs
        parent: pim-job-instance-csv-attribute-export-edit-form
        targetZone: content
        position: 100

    pim-job-instance-csv-attribute-export-edit-form-properties:
        module: pim/export/common/edit/properties
        parent: pim-job-instance-csv-attribute-export-edit-form-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone: container
        position: 100
        config:
            tabTitle: pim_enrich.form.job_instance.tab.properties.title

    pim-job-instance-csv-attribute-export-edit-form-history:
        module: pim/common/tab/history
        parent: pim-job-instance-csv-attribute-export-edit-form-tabs
        targetZone: container
        aclResourceId: pim_importexport_export_profile_history
        position: 120
        config:
            class: Akeneo\Component\Batch\Model\JobInstance
            title: pim_enrich.form.job_instance.tab.history.title

    pim-job-instance-csv-attribute-export-edit-form-properties-code:
        module: pim/export/common/edit/field/text
        parent: pim-job-instance-csv-attribute-export-edit-form-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: pim_enrich.form.job_instance.tab.properties.code.title
            readOnly: true

    pim-job-instance-csv-attribute-export-edit-form-properties-label:
        module: pim/export/common/edit/field/text
        parent: pim-job-instance-csv-attribute-export-edit-form-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_enrich.form.job_instance.tab.properties.label.title
            readOnly: false

    pim-job-instance-csv-attribute-export-edit-form-properties-file-path:
        module: pim/export/common/edit/field/text
        parent: pim-job-instance-csv-attribute-export-edit-form-properties
        position: 120
        targetZone: global-settings
        config:
            fieldCode: configuration.filePath
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.file_path.title
            tooltip: pim_enrich.form.job_instance.tab.properties.help.filePath.help

    pim-job-instance-csv-attribute-export-edit-form-properties-delimiter:
        module: pim/export/common/edit/field/text
        parent: pim-job-instance-csv-attribute-export-edit-form-properties
        position: 130
        targetZone: global-settings
        config:
            fieldCode: configuration.delimiter
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.delimiter.title
            tooltip: pim_enrich.form.job_instance.tab.properties.help.delimiter.help

    pim-job-instance-csv-attribute-export-edit-form-properties-enclosure:
        module: pim/export/common/edit/field/text
        parent: pim-job-instance-csv-attribute-export-edit-form-properties
        position: 140
        targetZone: global-settings
        config:
            fieldCode: configuration.enclosure
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.enclosure.title
            tooltip: pim_enrich.form.job_instance.tab.properties.help.enclosure.help

    pim-job-instance-csv-attribute-export-edit-form-properties-with-header:
        module: pim/export/common/edit/field/switch
        parent: pim-job-instance-csv-attribute-export-edit-form-properties
        position: 150
        targetZone: global-settings
        config:
            fieldCode: configuration.withHeader
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.with_header.title
            tooltip: pim_enrich.form.job_instance.tab.properties.help.withHeader.help

    pim-job-instance-csv-attribute-export-edit-form-label:
        module: pim/export/common/edit/label
        parent: pim-job-instance-csv-attribute-export-edit-form
        targetZone: title
        position: 100

    pim-job-instance-csv-attribute-export-edit-form-meta:
        module: pim/export/common/edit/meta
        parent: pim-job-instance-csv-attribute-export-edit-form
        targetZone: meta
        position: 100

    pim-job-instance-csv-attribute-export-edit-form-back-to-grid:
        module: pim/form/common/back-to-grid
        parent: pim-job-instance-csv-attribute-export-edit-form
        targetZone: back
        aclResourceId: pim_importexport_export_profile_index
        position: 80
        config:
            backUrl: pim_importexport_export_profile_index

    pim-job-instance-csv-attribute-export-edit-form-delete:
        module: pim/export/common/edit/delete
        parent: pim-job-instance-csv-attribute-export-edit-form
        targetZone: buttons
        aclResourceId: pim_importexport_export_profile_remove
        position: 100
        config:
            trans:
                title: confirmation.remove.job_instance
                content: pim_enrich.confirmation.delete_item
                success: flash.job_instance.removed
                failed: error.removing.job_instance
            redirect: pim_importexport_export_profile_index

    pim-job-instance-csv-attribute-export-edit-form-save-buttons:
        module: pim/form/common/save-buttons
        parent: pim-job-instance-csv-attribute-export-edit-form
        targetZone: buttons
        position: 120

    pim-job-instance-csv-attribute-export-edit-form-save:
        module: pim/job-instance-edit-form/save
        parent: pim-job-instance-csv-attribute-export-edit-form
        targetZone: buttons
        position: 0

    pim-job-instance-csv-attribute-export-edit-form-state:
        module: pim/form/common/state
        parent: pim-job-instance-csv-attribute-export-edit-form
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.variant_group.title

    pim-job-instance-csv-attribute-export-edit-form-validation:
        module: pim/export/common/edit/validation
        parent: pim-job-instance-csv-attribute-export-edit-form
