extensions:
    pim-job-instance-csv-product-export-edit-form:
        module: pim/form/common/edit-form

    pim-job-instance-csv-product-export-edit-form-cache-invalidator:
        module: pim/cache-invalidator
        parent: pim-job-instance-csv-product-export-edit-form
        position: 1000

    pim-job-instance-csv-product-export-edit-form-form-tabs:
        module: pim/form/common/form-tabs
        parent: pim-job-instance-csv-product-export-edit-form
        targetZone: content
        position: 100

    pim-job-instance-csv-product-export-edit-form-properties:
        module: pim/export/common/edit/properties
        parent: pim-job-instance-csv-product-export-edit-form-form-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone: container
        position: 100
        config:
            tabTitle: pim_enrich.form.job_instance.tab.properties.title

    pim-job-instance-csv-product-export-edit-form-content:
        module: pim/export/product/edit/content
        parent: pim-job-instance-csv-product-export-edit-form-form-tabs
        aclResourceId: pim_importexport_export_profile_content_edit
        targetZone: container
        position: 110
        config:
            tabTitle: pim_enrich.form.job_instance.tab.content.title

    pim-job-instance-csv-product-export-edit-form-history:
        module: pim/common/tab/history
        parent: pim-job-instance-csv-product-export-edit-form-form-tabs
        targetZone: container
        aclResourceId: pim_importexport_export_profile_history
        position: 120
        config:
            class: Akeneo\Component\Batch\Model\JobInstance
            title: pim_enrich.form.job_instance.tab.history.title

    pim-job-instance-csv-product-export-edit-form-properties-code:
        module: pim/export/common/edit/field/text
        parent: pim-job-instance-csv-product-export-edit-form-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: pim_enrich.form.job_instance.tab.properties.code.title
            readOnly: true

    pim-job-instance-csv-product-export-edit-form-properties-label:
        module: pim/export/common/edit/field/text
        parent: pim-job-instance-csv-product-export-edit-form-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_enrich.form.job_instance.tab.properties.label.title
            readOnly: false

    pim-job-instance-csv-product-export-edit-form-properties-decimal-separator:
        module: pim/export/product/edit/field/decimal-separator
        parent: pim-job-instance-csv-product-export-edit-form-properties
        position: 100
        targetZone: global-settings
        config:
            fieldCode: configuration.decimalSeparator
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.decimal_separator.title
            tooltip: pim_enrich.form.job_instance.tab.properties.help.decimal_separator.help

    pim-job-instance-csv-product-export-edit-form-properties-date-format:
        module: pim/export/product/edit/field/date-format
        parent: pim-job-instance-csv-product-export-edit-form-properties
        position: 110
        targetZone: global-settings
        config:
            fieldCode: configuration.dateFormat
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.date_format.title
            tooltip: pim_enrich.form.job_instance.tab.properties.help.date_format.help

    pim-job-instance-csv-product-export-edit-form-properties-file-path:
        module: pim/export/common/edit/field/text
        parent: pim-job-instance-csv-product-export-edit-form-properties
        position: 120
        targetZone: global-settings
        config:
            fieldCode: configuration.filePath
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.file_path.title
            tooltip: pim_enrich.form.job_instance.tab.properties.help.file_path.help

    pim-job-instance-csv-product-export-edit-form-properties-delimiter:
        module: pim/export/common/edit/field/text
        parent: pim-job-instance-csv-product-export-edit-form-properties
        position: 130
        targetZone: global-settings
        config:
            fieldCode: configuration.delimiter
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.delimiter.title
            tooltip: pim_enrich.form.job_instance.tab.properties.help.delimiter.help

    pim-job-instance-csv-product-export-edit-form-properties-enclosure:
        module: pim/export/common/edit/field/text
        parent: pim-job-instance-csv-product-export-edit-form-properties
        position: 140
        targetZone: global-settings
        config:
            fieldCode: configuration.enclosure
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.enclosure.title
            tooltip: pim_enrich.form.job_instance.tab.properties.help.enclosure.help

    pim-job-instance-csv-product-export-edit-form-properties-with-header:
        module: pim/export/common/edit/field/switch
        parent: pim-job-instance-csv-product-export-edit-form-properties
        position: 150
        targetZone: global-settings
        config:
            fieldCode: configuration.withHeader
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.with_header.title
            tooltip: pim_enrich.form.job_instance.tab.properties.help.with_header.help

    pim-job-instance-csv-product-export-edit-form-properties-with-media:
        module: pim/export/common/edit/field/switch
        parent: pim-job-instance-csv-product-export-edit-form-properties
        position: 160
        targetZone: global-settings
        config:
            fieldCode: configuration.with_media
            readOnly: false
            label: pim_enrich.form.job_instance.tab.properties.with_media.title
            tooltip: pim_enrich.form.job_instance.tab.properties.help.with_media.help

    pim-product-export-edit-cache-invalidator:
        module: pim/cache-invalidator
        parent: pim-job-instance-csv-product-export-edit-form-content
        position: 1000

    pim-job-instance-csv-product-export-edit-form-content-structure:
        module: pim/export/product/edit/content/structure
        parent: pim-job-instance-csv-product-export-edit-form-content
        targetZone: structure-filters
        position: 100

    pim-job-instance-csv-product-export-edit-form-label:
        module: pim/export/common/edit/label
        parent: pim-job-instance-csv-product-export-edit-form
        targetZone: title
        position: 100

    pim-job-instance-csv-product-export-edit-form-meta:
        module: pim/export/common/edit/meta
        parent: pim-job-instance-csv-product-export-edit-form
        targetZone: meta
        position: 100

    pim-job-instance-csv-product-export-edit-form-back-to-grid:
        module: pim/form/common/back-to-grid
        parent: pim-job-instance-csv-product-export-edit-form
        targetZone: back
        aclResourceId: pim_importexport_export_profile_index
        position: 80
        config:
            backUrl: pim_importexport_export_profile_index

    pim-job-instance-csv-product-export-edit-form-delete:
        module: pim/export/common/edit/delete
        parent: pim-job-instance-csv-product-export-edit-form
        targetZone: buttons
        aclResourceId: pim_importexport_export_profile_remove
        position: 100
        config:
            trans:
                title: confirmation.remove.job_instance
                content: pim_enrich.confirmation.delete_item
                success: flash.job_instance.removed
                failed: error.removing.job_instance
            redirect: pim_importexport_export_profile_index

    pim-job-instance-csv-product-export-edit-form-save-buttons:
        module: pim/form/common/save-buttons
        parent: pim-job-instance-csv-product-export-edit-form
        targetZone: buttons
        position: 120

    pim-job-instance-csv-product-export-edit-form-save:
        module: pim/job-instance-edit-form/save
        parent: pim-job-instance-csv-product-export-edit-form
        targetZone: buttons
        position: 0

    pim-job-instance-csv-product-export-edit-form-state:
        module: pim/form/common/state
        parent: pim-job-instance-csv-product-export-edit-form
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.variant_group.title


    pim-job-instance-csv-product-export-edit-form-content-structure-scope:
        module: pim/export/product/edit/content/structure/scope
        parent: pim-job-instance-csv-product-export-edit-form-content-structure
        targetZone: filters
        position: 90

    pim-job-instance-csv-product-export-edit-form-content-structure-locales:
        module: pim/export/product/edit/content/structure/locales
        parent: pim-job-instance-csv-product-export-edit-form-content-structure
        targetZone: filters
        position: 100

    pim-job-instance-csv-product-export-edit-form-content-structure-attributes:
        module: pim/export/product/edit/content/structure/attributes
        parent: pim-job-instance-csv-product-export-edit-form-content-structure
        targetZone: filters
        position: 110

    pim-job-instance-csv-product-export-edit-form-content-data:
        module: pim/export/product/edit/content/data
        parent: pim-job-instance-csv-product-export-edit-form-content
        targetZone: data-filters
        config:
            filters:
                -
                    field: family
                    view: akeneo-product-family-filter
                -
                    field: enabled
                    view: akeneo-product-enabled-filter
                -
                    field: completeness
                    view: akeneo-product-completeness-filter
                -
                    field: updated
                    view: akeneo-product-updated-filter
                -
                    field: categories
                    view: akeneo-product-category-filter

    pim-job-instance-csv-product-export-edit-form-content-default-attribute-filters:
        module: pim/export/product/edit/content/data/default-attribute-filters
        parent: pim-job-instance-csv-product-export-edit-form-content-data
        config:
            types: [pim_catalog_identifier]

    pim-job-instance-csv-product-export-edit-form-content-data-help:
        module: pim/export/product/edit/content/data/help
        parent: pim-job-instance-csv-product-export-edit-form-content-data

    pim-job-instance-csv-product-export-edit-form-validation:
        module: pim/export/product/edit/content/data/validation
        parent: pim-job-instance-csv-product-export-edit-form

    pim-job-instance-csv-product-export-edit-form-content-data-add-filter:
        module: pim/export/product/edit/content/data/add-filter
        parent: pim-job-instance-csv-product-export-edit-form-content-data
        targetZone: headings
