extensions:
    pim-job-instance-xlsx-product-export-show-form:
        module: pim/form/common/edit-form

    pim-job-instance-xlsx-product-export-show-form-form-tabs:
        module: pim/form/common/form-tabs
        parent: pim-job-instance-xlsx-product-export-show-form
        targetZone: content
        position: 100

    pim-job-instance-xlsx-product-export-show-form-properties:
        module: pim/export/common/edit/properties
        parent: pim-job-instance-xlsx-product-export-show-form-form-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone: container
        position: 100
        config:
            tabTitle: pim_enrich.form.job_instance.tab.properties.title

    pim-job-instance-xlsx-product-export-show-form-content:
        module: pim/export/product/edit/content
        parent: pim-job-instance-xlsx-product-export-show-form-form-tabs
        aclResourceId: pim_importexport_export_profile_content_edit
        targetZone: container
        position: 110
        config:
            tabTitle: pim_enrich.form.job_instance.tab.content.title

    pim-job-instance-xlsx-product-export-show-form-history:
        module: pim/common/tab/history
        parent: pim-job-instance-xlsx-product-export-show-form-form-tabs
        targetZone: container
        aclResourceId: pim_importexport_export_profile_history
        position: 120
        config:
            class: Akeneo\Component\Batch\Model\JobInstance
            title: pim_enrich.form.job_instance.tab.history.title

    pim-job-instance-xlsx-product-export-show-form-properties-code:
        module: pim/export/common/edit/field/text
        parent: pim-job-instance-xlsx-product-export-show-form-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: pim_enrich.form.job_instance.tab.properties.code.title
            readOnly: true

    pim-job-instance-xlsx-product-export-show-form-properties-label:
        module: pim/export/common/edit/field/text
        parent: pim-job-instance-xlsx-product-export-show-form-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_enrich.form.job_instance.tab.properties.label.title
            readOnly: true

    pim-job-instance-csv-product-export-show-form-properties-decimal-separator:
        module: pim/export/product/edit/field/decimal-separator
        parent: pim-job-instance-csv-product-export-show-form-properties
        position: 100
        targetZone: global-settings
        config:
            fieldCode: configuration.decimalSeparator
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.decimal_separator.title
            tooltip: pim_enrich.form.job_instance.tab.properties.help.decimal_separator.help

    pim-job-instance-xlsx-product-export-show-form-properties-date-format:
        module: pim/export/product/edit/field/date-format
        parent: pim-job-instance-xlsx-product-export-show-form-properties
        position: 110
        targetZone: global-settings
        config:
            fieldCode: configuration.dateFormat
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.date_format.title
            tooltip: pim_enrich.form.job_instance.tab.properties.help.date_format.help

    pim-job-instance-xlsx-product-export-show-form-properties-file-path:
        module: pim/export/common/edit/field/text
        parent: pim-job-instance-xlsx-product-export-show-form-properties
        position: 120
        targetZone: global-settings
        config:
            fieldCode: configuration.filePath
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.file_path.title
            tooltip: pim_enrich.form.job_instance.tab.properties.help.file_path.help

    pim-job-instance-xlsx-product-export-show-form-properties-lines-per-file:
        module: pim/export/common/edit/field/text
        parent: pim-job-instance-xlsx-product-export-show-form-properties
        position: 130
        targetZone: global-settings
        config:
            fieldCode: configuration.linesPerFile
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.lines_per_file.title
            tooltip: pim_enrich.form.job_instance.tab.properties.help.lines_per_file.help

    pim-job-instance-xlsx-product-export-show-form-properties-with-header:
        module: pim/export/common/edit/field/switch
        parent: pim-job-instance-xlsx-product-export-show-form-properties
        position: 140
        targetZone: global-settings
        config:
            fieldCode: configuration.withHeader
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.with_header.title
            tooltip: pim_enrich.form.job_instance.tab.properties.help.with_header.help

    pim-job-instance-xlsx-product-export-show-form-properties-with-media:
        module: pim/export/common/edit/field/switch
        parent: pim-job-instance-xlsx-product-export-show-form-properties
        position: 150
        targetZone: global-settings
        config:
            fieldCode: configuration.with_media
            readOnly: true
            label: pim_enrich.form.job_instance.tab.properties.with_media.title
            tooltip: pim_enrich.form.job_instance.tab.properties.help.with_media.help

    pim-job-instance-xlsx-product-export-show-form-content-structure:
        module: pim/export/product/edit/content/structure
        parent: pim-job-instance-xlsx-product-export-show-form-content
        targetZone: structure-filters
        position: 100

    pim-job-instance-xlsx-product-export-show-form-label:
        module: pim/export/common/edit/label
        parent: pim-job-instance-xlsx-product-export-show-form
        targetZone: title
        position: 100

    pim-job-instance-xlsx-product-export-show-form-meta:
        module: pim/export/common/edit/meta
        parent: pim-job-instance-xlsx-product-export-show-form
        targetZone: meta
        position: 100

    pim-job-instance-xlsx-product-export-show-form-back-to-grid:
        module: pim/form/common/back-to-grid
        parent: pim-job-instance-xlsx-product-export-show-form
        targetZone: back
        aclResourceId: pim_importexport_export_profile_index
        position: 80
        config:
            backUrl: pim_importexport_export_profile_index

    pim-job-instance-xlsx-product-export-show-form-content-structure-scope:
        module: pim/export/product/edit/content/structure/scope
        parent: pim-job-instance-xlsx-product-export-show-form-content-structure
        targetZone: filters
        position: 90

    pim-job-instance-xlsx-product-export-show-form-content-structure-locales:
        module: pim/export/product/edit/content/structure/locales
        parent: pim-job-instance-xlsx-product-export-show-form-content-structure
        targetZone: filters
        position: 100

    pim-job-instance-xlsx-product-export-show-form-content-structure-attributes:
        module: pim/export/product/edit/content/structure/attributes
        parent: pim-job-instance-xlsx-product-export-show-form-content-structure
        targetZone: filters
        position: 110

    pim-job-instance-xlsx-product-export-show-form-content-data:
        module: pim/export/product/edit/content/data
        parent: pim-job-instance-xlsx-product-export-show-form-content
        targetZone: data-filters
        config:
            filters:
                -
                    field: family
                    view: akeneo-product-family-filter
                -
                    field: enabled
                    view: akeneo-product-enabled-filter
                -
                    field: completeness
                    view: akeneo-product-completeness-filter
                -
                    field: updated
                    view: akeneo-product-updated-filter
                -
                    field: categories
                    view: akeneo-product-category-filter

    pim-job-instance-xlsx-product-export-show-form-content-default-attribute-filters:
        module: pim/export/product/edit/content/data/default-attribute-filters
        parent: pim-job-instance-xlsx-product-export-show-form-content-data
        config:
            types: [pim_catalog_identifier]

    pim-job-instance-xlsx-product-export-show-form-content-data-help:
        module: pim/export/product/edit/content/data/help
        parent: pim-job-instance-xlsx-product-export-show-form-content-data

    pim-job-instance-xlsx-product-export-show-form-edit:
        module: pim/common/redirect
        parent: pim-job-instance-xlsx-product-export-show-form
        targetZone: buttons
        position: 100
        config:
            label: pim_enrich.form.job_instance.button.edit.title
            route: pim_importexport_export_profile_edit
            identifier:
                path: code
                name: code

    pim-job-instance-xlsx-product-export-show-form-launch:
        module: pim/export/common/edit/launch
        parent: pim-job-instance-xlsx-product-export-show-form
        targetZone: buttons
        position: 110
        config:
            label: pim_enrich.form.job_instance.button.export.title
            route: pim_enrich_job_instance_rest_launch
            identifier:
                path: code
                name: code
